services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: hanainplan-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./datacode.sql:/docker-entrypoint-initdb.d/02-datacode.sql
    networks:
      - hanainplan-network
    restart: unless-stopped


  # Spring Boot 애플리케이션
  hanainplan-app:
    build: .
    container_name: hanainplan-spring-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - hanainplan-network
    restart: unless-stopped

  # 관리 도구들 (선택사항)

#  mongo-express:
#    image: mongo-express
#    container_name: hanainplan-mongo-express
#    depends_on:
#      - mongodb
#    ports:
#      - "8082:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
#      ME_CONFIG_MONGODB_SERVER: mongodb
#    networks:
#      - hanainplan-network
#
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: hanainplan-redis-commander
#    depends_on:
#      - redis
#    ports:
#      - "8083:8081"
#    environment:
#      REDIS_HOSTS: local:redis:6379
#    networks:
#      - hanainplan-network

volumes:
  mysql_data:

networks:
  hanainplan-network:
    driver: bridge